<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<url>
		<loc>{{url('/')}}</loc>
		<changefreq>always</changefreq>
	</url>
	<url>
		<loc>{{url('/about')}}</loc>
		<changefreq>hourly</changefreq>
	</url>
	<url>
		<loc>{{url('/team')}}</loc>
		<changefreq>hourly</changefreq>
	</url>
	<url>
		<loc>{{url('/contact')}}</loc>
		<changefreq>hourly</changefreq>
	</url>
	<url>
		<loc>{{url('/archive')}}</loc>
		<changefreq>hourly</changefreq>
	</url>
	<url>
		<loc>{{url('/terms')}}</loc>
		<changefreq>hourly</changefreq>
	</url>
	<url>
		<loc>{{url('/privacy-policy')}}</loc>
		<changefreq>hourly</changefreq>
	</url>
	<url>
		<loc>{{url('/advertisement')}}</loc>
		<changefreq>hourly</changefreq>
	</url>
	<url>
		<loc>{{url('/links/social-media')}}</loc>
		<changefreq>hourly</changefreq>
	</url>
	<url>
		<loc>{{url('/bn-converter')}}</loc>
		<changefreq>hourly</changefreq>
	</url>
	<url>
		<loc>{{url('/categories')}}</loc>
		<changefreq>hourly</changefreq>
	</url>
</urlset>